version: '3.4'
services:
  SAR_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/_results/EA31337-Lite_SAR_Active.set
      TEST_REPORT_NAME: EA31337-Lite_SAR_Active
      SET_PARAMS: SAR1_Active,SAR5_Active,SAR15_Active,SAR30_Active
      RUN_ON_SUCCESS: for tf in 1 5 15 30; do input_copy "SAR$${tf}_Active" "$${SETFILE}" /opt/lite/ea-input.mqh; done
  SAR1_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/SAR/Strategy-SAR-SAR1_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_SAR1_Active.set
      TEST_REPORT_NAME: EA31337-Lite_SAR1_Active
      RUN_ON_SUCCESS: input_copy SAR1_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  SAR5_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/SAR/Strategy-SAR-SAR5_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_SAR5_Active.set
      TEST_REPORT_NAME: EA31337-Lite_SAR5_Active
      RUN_ON_SUCCESS: input_copy SAR5_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  SAR15_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/SAR/Strategy-SAR-SAR15_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_SAR15_Active.set
      TEST_REPORT_NAME: EA31337-Lite_SAR15_Active
      RUN_ON_SUCCESS: input_copy SAR15_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  SAR30_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/SAR/Strategy-SAR-SAR30_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_SAR30_Active.set
      TEST_REPORT_NAME: EA31337-Lite_SAR30_Active
      RUN_ON_SUCCESS: input_copy SAR30_Active "$${SETFILE}" /opt/lite/ea-input.mqh
