version: '3.4'
services:
  Alligator_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/_results/EA31337-Lite_Alligator_Active.set
      TEST_REPORT_NAME: EA31337-Lite_Alligator_Active
      SET_PARAMS: Alligator1_Active,Alligator5_Active,Alligator15_Active,Alligator30_Active
      RUN_ON_SUCCESS: for tf in 1 5 15 30; do input_copy "Alligator$${tf}_Active" "$${SETFILE}" /opt/lite/ea-input.mqh; done
  Alligator1_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/Alligator/Strategy-Alligator-Alligator1_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_Alligator1_Active.set
      TEST_REPORT_NAME: EA31337-Lite_Alligator1_Active
      RUN_ON_SUCCESS: input_copy Alligator1_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  Alligator5_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/Alligator/Strategy-Alligator-Alligator5_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_Alligator5_Active.set
      TEST_REPORT_NAME: EA31337-Lite_Alligator5_Active
      RUN_ON_SUCCESS: input_copy Alligator5_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  Alligator15_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/Alligator/Strategy-Alligator-Alligator15_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_Alligator15_Active.set
      TEST_REPORT_NAME: EA31337-Lite_Alligator15_Active
      RUN_ON_SUCCESS: input_copy Alligator15_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  Alligator30_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/Alligator/Strategy-Alligator-Alligator30_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_Alligator30_Active.set
      TEST_REPORT_NAME: EA31337-Lite_Alligator30_Active
      RUN_ON_SUCCESS: input_copy Alligator30_Active "$${SETFILE}" /opt/lite/ea-input.mqh
