version: '3.4'
services:
  ADX_Backtest_2018:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ../../../../..:/opt/EA
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Lite_ADX.set
      TEST_REPORT_NAME: "EA31337-Lite_ADX[2018]"
  ADX1_Backtest_2018:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ../../../../..:/opt/EA
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Lite_ADX1.set
      TEST_REPORT_NAME: "EA31337-Lite_ADX1[2018]"
  ADX5_Backtest_2018:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ../../../../..:/opt/EA
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Lite_ADX5.set
      TEST_REPORT_NAME: "EA31337-Lite_ADX5[2018]"
  ADX15_Backtest_2018:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ../../../../..:/opt/EA
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Lite_ADX15.set
      TEST_REPORT_NAME: 'EA31337-Lite_ADX15[2018]'
  ADX30_Backtest_2018:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ../../../../..:/opt/EA
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Lite_ADX30.set
      TEST_REPORT_NAME: "EA31337-Lite_ADX30[2018]"
