---
version: '3.4'
services:
  AC_Backtest_2018:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ../../../../..:/opt/EA
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Lite_AC.set
      TEST_REPORT_NAME: "EA31337-Lite_AC[2018]"
  AC1_Backtest_2018:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ../../../../..:/opt/EA
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Lite_AC1.set
      TEST_REPORT_NAME: "EA31337-Lite_AC1[2018]"
  AC5_Backtest_2018:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ../../../../..:/opt/EA
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Lite_AC5.set
      TEST_REPORT_NAME: "EA31337-Lite_AC5[2018]"
  AC15_Backtest_2018:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ../../../../..:/opt/EA
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Lite_AC15.set
      TEST_REPORT_NAME: 'EA31337-Lite_AC15[2018]'
  AC30_Backtest_2018:
    command: run_backtest -v
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./sets:/opt/sets:rw
    - ../../../../..:/opt/EA
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      SETFILE: /opt/sets/EA31337-Lite_AC30.set
      TEST_REPORT_NAME: "EA31337-Lite_AC30[2018]"
