language: generic
services:
- docker
addons:
  apt:
    packages:
    - shellcheck
env:
  global:
  - CWD=$TRAVIS_BUILD_DIR
  matrix:
  - CMD="cd docker/tests/lite; docker-compose build --build-arg UID=$UID test_2018_01; docker-compose run test_2018_01"
  - CMD="cd docker/tests/advanced; docker-compose build --build-arg UID=$UID test_2018_01; docker-compose run test_2018_01"
  - CMD="cd docker/tests/rider; docker-compose build --build-arg UID=$UID test_2018_01; docker-compose run test_2018_01"
  - |
    DOCKER_LOGIN='eval [[ -n $DOCKER_PASSWORD ]] && docker login -u $DOCKER_USERNAME --password-stdin <<<$DOCKER_PASSWORD || exit 0'
    DOCKER_REPO="ea31337/ea31337:${TRAVIS_BRANCH//master/latest}"
    DOCKER_BUILD="DOCKER_BUILDKIT=1 docker build --target ea31337 -t ${DOCKER_REPO} ."
    CMD="${DOCKER_LOGIN} && ${DOCKER_BUILD} && [[ $TRAVIS_PULL_REQUEST = false ]] && docker push $DOCKER_REPO"
  - |
    CMD="docker run -v $CWD:/opt/EA:rw ea31337/ea-tester:dev 'for v in Lite-Backtest Advanced-Backtest Rider-Backtest Lite-Optimize Advanced-Optimize Rider-Optimize; do make -C /opt/EA \$v; done'"
    DEPLOY=1
matrix:
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
before_install:
- ulimit -a && free -m
install:
before_script:
- docker --version
- docker images
- test -n "$OPT_TRACE" && set -x || true
script:
- bash -n scripts/*.sh; shellcheck scripts/*.sh conf/*/*.sh
- echo $CMD
- eval $CMD
after_script:
- set +x
- git diff
after_success:
after_failure:
before_deploy:
- ls -1
deploy:
  provider: releases
  api_key:
  - secure: xNMEGaI6r/R+1yponEaPvinkFnYv3xJLvzhiTzJEGzOgKaqiCYaRWgM5e448iaCJeOb+mxLWt2zwu9MlmfWHVWn5bC4ozDZRAkpcui6lKlFUdoNAnAdyZ5+lmLeu1Botja4EGb/XewpiCcwQAt5+/HH+v3xbozeSMxBCiO5p74xSA3cc2uzUHp+hHzNZ8tjUA8lr4DwuiGX+irwPxcCVTurlUH6EHFvMlTy2w0i7zElwgyOR0x4GL4YdbfuUdESzadr4IENrGETNAi9PwVsUixJqpsdBtfyeUuMiUR0pPHQgFHMEXVwLrh4VfFZRabamziYt1PAsxyVkHlvPWiu7ffeDSd87xCAuQYHHMmWKTo5FCR6fr9qQcVq36nEqZkQ0pvv9T2lm2i4CAqZWIQE+yWMByIVFuZLZejV4zhMYu6mFpUAhJMmKcrFimvLaYNSqMIZxE9XNhE3wXTjeWxr/7unBOjzuCR8MXMqv7SkfJdmhvFPOwdH2GfqBaqoSbq9f7Bt8czoAZZkjZcvXxKwQR33QjOUX5WYwOCFHfkIwEZ6VFZhw1dg01HXv8tq7GVpwpjHwJeFJS5HzdB40Eh/TKkio/pl1YgBF17ne7NNp0uaUlbeJ70iuh2iL5eRaBAZW/MDi9/w4ZSAPzeR22JOgwuaI2hUm2kDUyfJS7Ib8ZjE=
  file:
    - "*.ex4"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: EA31337/EA31337
    condition: "$DEPLOY = 1"
    tags: true
after_deploy:
- make clean
