language: generic
sudo: required
group: deprecated-2017Q4
services:
  - docker
addons:
  apt:
    packages:
    - shellcheck
env:
  global:
  - CWD=$TRAVIS_BUILD_DIR
  - IS_PULL=$([[ '$TRAVIS_PULL_REQUEST' = 'false' ]]; echo $?)
  - DOCKER_BUILDKIT=1
  - DOCKER_TAG=$([[ "$TRAVIS_BRANCH" == "master" ]] && echo "latest" || echo ${TRAVIS_BRANCH////-})
  - DOCKER_REPO="ea31337/ea31337:$DOCKER_TAG"
  - DOCKER_LOGIN='eval [[ -n "$DOCKER_PASSWORD" ]] && docker login -u $DOCKER_USERNAME --password-stdin <<<$DOCKER_PASSWORD || exit 0'
  - DOCKER_PUSH='docker push $DOCKER_REPO'
  matrix:
  - CMD="cd docker/tests/lite; docker-compose build --build-arg UID=$UID test_2018_01; docker-compose run test_2018_01"
  - CMD="cd docker/tests/advanced; docker-compose build --build-arg UID=$UID test_2018_01; docker-compose run test_2018_01"
  - CMD="cd docker/tests/rider; docker-compose build --build-arg UID=$UID test_2018_01; docker-compose run test_2018_01"
  - CMD="${DOCKER_LOGIN} && docker build --target ea31337-all -t ${DOCKER_REPO} . && [[ $IS_PULL -eq 0 ]] && ${DOCKER_PUSH}"
matrix:
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
before_install:
- ulimit -a && free -m
install:
before_script:
- docker images
script:
- bash -n scripts/*.sh; shellcheck scripts/*.sh conf/*/*.sh
- echo $CMD
- eval $CMD
after_script:
- set +x
- git diff
after_success:
after_failure:
