version: '3.4'
services:
  SAR1_OpenCondition1:
    command: run_backtest -v
    image: ea31337:advanced-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-advanced-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/advanced:/opt/advanced:rw
    - ../../../../../../../EA-Tester/scripts:/opt/scripts:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/_results/EA31337-Advanced_SAR1_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Advanced_SAR1_OpenCondition1
      SET_PARAMS: SAR1_OpenCondition1
      RUN_ON_SUCCESS: input_copy SAR1_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  SAR5_OpenCondition1:
    command: run_backtest -v
    image: ea31337:advanced-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-advanced-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/advanced:/opt/advanced:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/_results/EA31337-Advanced_SAR5_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Advanced_SAR5_OpenCondition1
      SET_PARAMS: SAR5_OpenCondition1
      RUN_ON_SUCCESS: input_copy SAR5_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  SAR15_OpenCondition1:
    command: run_backtest -v
    image: ea31337:advanced-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-advanced-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/advanced:/opt/advanced:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/_results/EA31337-Advanced_SAR15_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Advanced_SAR15_OpenCondition1
      SET_PARAMS: SAR15_OpenCondition1
      RUN_ON_SUCCESS: input_copy SAR15_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  SAR30_OpenCondition1:
    command: run_backtest -v
    image: ea31337:advanced-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-advanced-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/advanced:/opt/advanced:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/_results/EA31337-Advanced_SAR30_OpenCondition1.set
      TEST_REPORT_NAME: EA31337-Advanced_SAR30_OpenCondition1
      SET_PARAMS: SAR30_OpenCondition1
      RUN_ON_SUCCESS: input_copy SAR30_OpenCondition1 "$${SETFILE}" /opt/advanced/ea-input.mqh
  SAR1_OpenCondition2:
    command: run_backtest -v
    image: ea31337:advanced-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-advanced-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/advanced:/opt/advanced:rw
    - ../../../../../../../EA-Tester/scripts:/opt/scripts:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/_results/EA31337-Advanced_SAR1_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Advanced_SAR1_OpenCondition2
      SET_PARAMS: SAR1_OpenCondition2
      RUN_ON_SUCCESS: input_copy SAR1_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
  SAR5_OpenCondition2:
    command: run_backtest -v
    image: ea31337:advanced-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-advanced-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/advanced:/opt/advanced:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/_results/EA31337-Advanced_SAR5_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Advanced_SAR5_OpenCondition2
      SET_PARAMS: SAR5_OpenCondition2
      RUN_ON_SUCCESS: input_copy SAR5_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
  SAR15_OpenCondition2:
    command: run_backtest -v
    image: ea31337:advanced-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-advanced-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/advanced:/opt/advanced:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/_results/EA31337-Advanced_SAR15_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Advanced_SAR15_OpenCondition2
      SET_PARAMS: SAR15_OpenCondition2
      RUN_ON_SUCCESS: input_copy SAR15_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
  SAR30_OpenCondition2:
    command: run_backtest -v
    image: ea31337:advanced-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-advanced-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/advanced:/opt/advanced:rw
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/_results/EA31337-Advanced_SAR30_OpenCondition2.set
      TEST_REPORT_NAME: EA31337-Advanced_SAR30_OpenCondition2
      SET_PARAMS: SAR30_OpenCondition2
      RUN_ON_SUCCESS: input_copy SAR30_OpenCondition2 "$${SETFILE}" /opt/advanced/ea-input.mqh
