version: '3.4'
services:
  Alligator_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/Alligator/Strategy-Alligator-All-Alligator_TrailingStopMethod.rule
      SETFILE: /opt/_results/EA31337-Lite_Alligator_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-Lite_Alligator_TrailingStopMethod
      RUN_ON_SUCCESS: input_copy Alligator_TrailingStopMethod "$${SETFILE}" /opt/lite/ea-input.mqh
  Alligator_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/Alligator/Strategy-Alligator-All-Alligator_TrailingProfitMethod.rule
      SETFILE: /opt/_results/EA31337-Lite_Alligator_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-Lite_Alligator_TrailingProfitMethod
      RUN_ON_SUCCESS: input_copy Alligator_TrailingProfitMethod "$${SETFILE}" /opt/lite/ea-input.mqh
