version: '3.4'
services:
  Fractals_Shift:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    - ../../../../../../src/include/EA31337/advanced:/opt/advanced:rw
    - ../../../../../../src/include/EA31337/rider:/opt/rider:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/Fractals/Strategy-Fractals-All-Fractals_Shift.rule
      SETFILE: /opt/_results/EA31337-Lite_Fractals_Shift.set
      TEST_REPORT_NAME: EA31337-Lite_Fractals_Shift
      RUN_ON_SUCCESS: input_copy Fractals_Shift "$${SETFILE}" /opt/lite/ea-input.mqh /opt/advanced/ea-input.mqh /opt/rider/ea-input.mqh
