version: '3.4'
services:
  RSI_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester.ini
    environment:
      SETFILE: /opt/_results/EA31337-Lite_RSI_Active.set
      TEST_REPORT_NAME: EA31337-Lite_RSI_Active
      SET_PARAMS: RSI1_Active,RSI5_Active,RSI15_Active,RSI30_Active
      RUN_ON_SUCCESS: for tf in 1 5 15 30; do input_copy "RSI$${tf}_Active" "$${SETFILE}" /opt/lite/ea-input.mqh; done
  RSI1_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/RSI/Strategy-RSI-RSI1_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_RSI1_Active.set
      TEST_REPORT_NAME: EA31337-Lite_RSI1_Active
      RUN_ON_SUCCESS: input_copy RSI1_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  RSI5_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/RSI/Strategy-RSI-RSI5_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_RSI5_Active.set
      TEST_REPORT_NAME: EA31337-Lite_RSI5_Active
      RUN_ON_SUCCESS: input_copy RSI5_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  RSI15_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/RSI/Strategy-RSI-RSI15_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_RSI15_Active.set
      TEST_REPORT_NAME: EA31337-Lite_RSI15_Active
      RUN_ON_SUCCESS: input_copy RSI15_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  RSI30_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/RSI/Strategy-RSI-RSI30_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_RSI30_Active.set
      TEST_REPORT_NAME: EA31337-Lite_RSI30_Active
      RUN_ON_SUCCESS: input_copy RSI30_Active "$${SETFILE}" /opt/lite/ea-input.mqh
