version: '3.4'
services:
  RSI_TrailingStopMethod:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 1-6
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      INCLUDE: /opt/rules/Strategies/RSI/Strategy-RSI-All-RSI_TrailingStopMethod.rule
      SETFILE: /opt/_results/EA31337-Lite_RSI_TrailingStopMethod.set
      TEST_REPORT_NAME: EA31337-Lite_RSI_TrailingStopMethod
      RUN_ON_SUCCESS: input_copy RSI_TrailingStopMethod "$${SETFILE}" /opt/lite/ea-input.mqh
  RSI_TrailingProfitMethod:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
    env_file: ../../../EA-Tester.ini
    environment:
      BT_MONTHS: 1-6
      EA_OPTS: maxdrawdown_enable=1,maxdrawdown=2
      INCLUDE: /opt/rules/Strategies/RSI/Strategy-RSI-All-RSI_TrailingProfitMethod.rule
      SETFILE: /opt/_results/EA31337-Lite_RSI_TrailingProfitMethod.set
      TEST_REPORT_NAME: EA31337-Lite_RSI_TrailingProfitMethod
      RUN_ON_SUCCESS: input_copy RSI_TrailingProfitMethod "$${SETFILE}" /opt/lite/ea-input.mqh
