version: '3.4'
services:
  CCI1_SignalMethod:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/CCI/Strategy-CCI-CCI1_SignalMethod.rule
      SETFILE: /opt/_results/EA31337-Lite_CCI1_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Lite_CCI1_SignalMethod
      RUN_ON_SUCCESS: input_copy CCI1_SignalMethod "$${SETFILE}" /opt/lite/ea-input.mqh
  CCI5_SignalMethod:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/CCI/Strategy-CCI-CCI5_SignalMethod.rule
      SETFILE: /opt/_results/EA31337-Lite_CCI5_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Lite_CCI5_SignalMethod
      RUN_ON_SUCCESS: input_copy CCI5_SignalMethod "$${SETFILE}" /opt/lite/ea-input.mqh
  CCI15_SignalMethod:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/CCI/Strategy-CCI-CCI15_SignalMethod.rule
      SETFILE: /opt/_results/EA31337-Lite_CCI15_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Lite_CCI15_SignalMethod
      RUN_ON_SUCCESS: input_copy CCI15_SignalMethod "$${SETFILE}" /opt/lite/ea-input.mqh
  CCI30_SignalMethod:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester.ini
    environment:
      INCLUDE: /opt/rules/Strategies/CCI/Strategy-CCI-CCI30_SignalMethod.rule
      SETFILE: /opt/_results/EA31337-Lite_CCI30_SignalMethod.set
      TEST_REPORT_NAME: EA31337-Lite_CCI30_SignalMethod
      RUN_ON_SUCCESS: input_copy CCI30_SignalMethod "$${SETFILE}" /opt/lite/ea-input.mqh
