version: '3.4'
services:
  backtest_2017_100k:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2017
    build:
      context: ../../../../..
      target: ea31337-lite-eurusd-2017
    volumes:
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      BT_YEARS: 2017
      BT_DEPOSIT: 100000
      TEST_REPORT_NAME: EA31337-Advanced_2017_100k
  backtest_2017_10k:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2017
    build:
      context: ../../../../..
      target: ea31337-lite-eurusd-2017
    volumes:
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      BT_YEARS: 2017
      BT_DEPOSIT: 10000
      TEST_REPORT_NAME: EA31337-Advanced_2017_10k
  backtest_2017_1k:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2017
    build:
      context: ../../../../..
      target: ea31337-lite-eurusd-2017
    volumes:
    - ./_results:/opt/_results:rw
    env_file: ../EA-Tester.ini
    environment:
      BT_YEARS: 2017
      BT_DEPOSIT: 1000
      TEST_REPORT_NAME: EA31337-Advanced_2017_1k
