version: '3.4'
services:
  WPR1_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester-params.txt
    environment:
      INCLUDE: /opt/rules/Strategies/WPR/Strategy-WPR-WPR1_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_WPR1_Active.set
      TEST_REPORT_NAME: EA31337-Lite_WPR1_Active
      RUN_ON_SUCCESS: input_copy WPR1_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  WPR5_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester-params.txt
    environment:
      INCLUDE: /opt/rules/Strategies/WPR/Strategy-WPR-WPR5_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_WPR5_Active.set
      TEST_REPORT_NAME: EA31337-Lite_WPR5_Active
      RUN_ON_SUCCESS: input_copy WPR5_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  WPR15_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester-params.txt
    environment:
      INCLUDE: /opt/rules/Strategies/WPR/Strategy-WPR-WPR15_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_WPR15_Active.set
      TEST_REPORT_NAME: EA31337-Lite_WPR15_Active
      RUN_ON_SUCCESS: input_copy WPR15_Active "$${SETFILE}" /opt/lite/ea-input.mqh
  WPR30_Active:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../../../EA-Tester-params.txt
    environment:
      INCLUDE: /opt/rules/Strategies/WPR/Strategy-WPR-WPR30_Active.rule
      SETFILE: /opt/_results/EA31337-Lite_WPR30_Active.set
      TEST_REPORT_NAME: EA31337-Lite_WPR30_Active
      RUN_ON_SUCCESS: input_copy WPR30_Active "$${SETFILE}" /opt/lite/ea-input.mqh
