version: '3.4'
services:
  WPR_Period:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts:rw
    env_file: ../../../.env
    environment:
      INCLUDE: /opt/rules/Strategies/WPR/Strategy-WPR-All-WPR_Period.rule
      SETFILE: /opt/_results/EA31337-Lite_WPR_Period.set
      TEST_REPORT_NAME: EA31337-Lite_WPR_Period
      RUN_ON_SUCCESS: input_copy WPR_Period "$${SETFILE}" /opt/lite/ea-input.mqh
  WPR_Period_Ratio:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts:rw
    env_file: ../../../.env
    environment:
      INCLUDE: /opt/rules/Strategies/WPR/Strategy-WPR-All-WPR_Period_Ratio.rule
      SETFILE: /opt/_results/EA31337-Lite_WPR_Period_Ratio.set
      TEST_REPORT_NAME: EA31337-Lite_WPR_Period_Ratio
      RUN_ON_SUCCESS: input_copy WPR_Period_Ratio "$${SETFILE}" /opt/lite/ea-input.mqh
  WPR_SignalLevel:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts:rw
    env_file: ../../../.env
    environment:
      INCLUDE: /opt/rules/Strategies/WPR/Strategy-WPR-All-WPR_SignalLevel.rule
      SETFILE: /opt/_results/EA31337-Lite_WPR_SignalLevel.set
      TEST_REPORT_NAME: EA31337-Lite_WPR_SignalLevel
      RUN_ON_SUCCESS: input_copy WPR_SignalLevel "$${SETFILE}" /opt/lite/ea-input.mqh
  WPR_Shift:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts:rw
    env_file: ../../../.env
    environment:
      INCLUDE: /opt/rules/Strategies/WPR/Strategy-WPR-All-WPR_Shift.rule
      SETFILE: /opt/_results/EA31337-Lite_WPR_Shift.set
      TEST_REPORT_NAME: EA31337-Lite_WPR_Shift
      RUN_ON_SUCCESS: input_copy WPR_Shift "$${SETFILE}" /opt/lite/ea-input.mqh
