version: '3.4'
# Note: In case of timeout, run with: DOCKER_CLIENT_TIMEOUT=600 COMPOSE_HTTP_TIMEOUT=600
services:
# Alligator
  Alligator_Backtest_2018:
    command: run_backtest -v
    image: ea31337:eurusd-2018
    build:
      context: ../../../../..
      target: ea31337-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../EA-Tester.ini
    environment:
      BT_YEARS: 2018
      SETFILE: /opt/_results/EA31337-Lite_Alligator.set
      TEST_REPORT_NAME: "EA31337-Lite_Alligator[2018]"
    deploy:
      restart_policy:
        condition: none
  Alligator1_Backtest_2018:
    command: run_backtest -v
    image: ea31337:eurusd-2018
    build:
      context: ../../../../..
      target: ea31337-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../EA-Tester.ini
    environment:
      BT_YEARS: 2018
      SETFILE: /opt/_results/EA31337-Lite_Alligator1.set
      TEST_REPORT_NAME: "EA31337-Lite_Alligator1[2018]"
    deploy:
      restart_policy:
        condition: none
  Alligator5_Backtest_2018:
    command: run_backtest -v
    image: ea31337:eurusd-2018
    build:
      context: ../../../../..
      target: ea31337-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../EA-Tester.ini
    environment:
      BT_YEARS: 2018
      SETFILE: /opt/_results/EA31337-Lite_Alligator5.set
      TEST_REPORT_NAME: "EA31337-Lite_Alligator5[2018]"
    deploy:
      restart_policy:
        condition: none
  Alligator15_Backtest_2018:
    command: run_backtest -v
    image: ea31337:eurusd-2018
    build:
      context: ../../../../..
      target: ea31337-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../EA-Tester.ini
    environment:
      BT_YEARS: 2018
      SETFILE: /opt/_results/EA31337-Lite_Alligator15.set
      TEST_REPORT_NAME: "EA31337-Lite_Alligator15[2018]"
    deploy:
      restart_policy:
        condition: none
  Alligator30_Backtest_2018:
    command: run_backtest -v
    image: ea31337:eurusd-2018
    build:
      context: ../../../../..
      target: ea31337-eurusd-2018
    volumes:
    - ./_results:/opt/_results:rw
    - ../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: ../EA-Tester.ini
    environment:
      BT_YEARS: 2018
      SETFILE: /opt/_results/EA31337-Lite_Alligator30.set
      TEST_REPORT_NAME: "EA31337-Lite_Alligator30[2018]"
    deploy:
      restart_policy:
        condition: none
