version: '3.4'
services:
  Bands_Period:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ../../../../../../src:/opt/src
    - ../../../../_rules:/opt/rules
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: .env
    environment:
      INCLUDE: /opt/rules/Strategies/Bands/Strategy-Bands-All-Bands_Period.rule
      SETFILE: /opt/_results/EA31337-Lite_Bands_Period.set
      TEST_REPORT_NAME: EA31337-Lite_Bands_Period
      RUN_ON_SUCCESS: input_copy Bands_Period "$${SETFILE}" /opt/lite/ea-input.mqh
  Bands_Applied_Price:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ../../../../../../src:/opt/src
    - ../../../../_rules:/opt/rules
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: .env
    environment:
      INCLUDE: /opt/rules/Strategies/Bands/Strategy-Bands-All-Bands_Applied_Price.rule
      SETFILE: /opt/_results/EA31337-Lite_Bands_Applied_Price.set
      TEST_REPORT_NAME: EA31337-Lite_Bands_Applied_Price
      RUN_ON_SUCCESS: input_copy Bands_Applied_Price "$${SETFILE}" /opt/lite/ea-input.mqh
  Bands_Deviation:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ../../../../../../src:/opt/src
    - ../../../../_rules:/opt/rules
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: .env
    environment:
      INCLUDE: /opt/rules/Strategies/Bands/Strategy-Bands-All-Bands_Deviation.rule
      SETFILE: /opt/_results/EA31337-Lite_Bands_Deviation.set
      TEST_REPORT_NAME: EA31337-Lite_Bands_Deviation
      RUN_ON_SUCCESS: input_copy Bands_Deviation "$${SETFILE}" /opt/lite/ea-input.mqh
  Bands_Deviation_Ratio:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ../../../../../../src:/opt/src
    - ../../../../_rules:/opt/rules
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: .env
    environment:
      INCLUDE: /opt/rules/Strategies/Bands/Strategy-Bands-All-Bands_Deviation_Ratio.rule
      SETFILE: /opt/_results/EA31337-Lite_Bands_Deviation_Ratio.set
      TEST_REPORT_NAME: EA31337-Lite_Bands_Deviation_Ratio
      RUN_ON_SUCCESS: input_copy Bands_Deviation_Ratio "$${SETFILE}" /opt/lite/ea-input.mqh
  Bands_SignalLevel:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ../../../../../../src:/opt/src
    - ../../../../_rules:/opt/rules
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: .env
    environment:
      INCLUDE: /opt/rules/Strategies/Bands/Strategy-Bands-All-Bands_SignalLevel.rule
      SETFILE: /opt/_results/EA31337-Lite_Bands_SignalLevel.set
      TEST_REPORT_NAME: EA31337-Lite_Bands_SignalLevel
      RUN_ON_SUCCESS: input_copy Bands_SignalLevel "$${SETFILE}" /opt/lite/ea-input.mqh
  Bands_Shift:
    command: run_backtest -v
    image: ea31337:lite-eurusd-2018
    build:
      context: ../../../../../..
      target: ea31337-lite-eurusd-2018
    volumes:
    - ../../../../../../src:/opt/src
    - ../../../../_rules:/opt/rules
    - ./_results:/opt/_results:rw
    - ../../../../../../src/include/EA31337/lite:/opt/lite:rw
#   - ../../../../../../../EA-Tester/scripts:/opt/scripts
    env_file: .env
    environment:
      INCLUDE: /opt/rules/Strategies/Bands/Strategy-Bands-All-Bands_Shift.rule
      SETFILE: /opt/_results/EA31337-Lite_Bands_Shift.set
      TEST_REPORT_NAME: EA31337-Lite_Bands_Shift
      RUN_ON_SUCCESS: for p in Shift Shift_Far; do input_copy "Bands_$${p}" "$${SETFILE}" /opt/lite/ea-input.mqh; done
