---
name: Backtest

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'v*-backtest'
  release:
    types:
      - published

jobs:

  Compile-IndicatorsOther:
    defaults:
      run:
        shell: powershell
        working-directory: src/indicators-other
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/checkout@v3
        with:
          path: Include/EA31337-classes
          ref: v2.013
          repository: EA31337/EA31337-classes
      - name: Compile (build 2361)
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 5.0.0.2361
          path: src/indicators-other/**/*.mq?
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
      - name: Upload indicator artifacts
        uses: actions/upload-artifact@v3
        with:
          name: indicators-other
          path: '**/*.ex?'

  Compile-EA:

    defaults:
      run:
        shell: powershell
        working-directory: src
    needs: [Compile-IndicatorsOther]
    runs-on: windows-latest

    strategy:
      matrix:
        mode:
          - Lite
          - Advanced
          - Rider
        mode2:
          - __resource__

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/download-artifact@v3
        with:
          name: indicators-other
          path: .

      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'

      - run: Get-Location

      # @fixme: https://github.com/actions/upload-artifact/issues/87
      - name: Link indicators
        run: New-Item -ItemType SymbolicLink -Path "../indicators-other" -Target "indicators-other"

      - name: Enables CLI mode
        run: echo '#define __cli__' > include/common/mode.h

      - name: Enables resource mode
        if: matrix.mode2 != '__resource__'
        run: echo '#define __resource__' > include/common/mode.h

      - name: Enables Advanced mode
        if: matrix.mode == 'Advanced'
        run: echo '#define __advanced__' >> include/common/mode.h

      - name: Enables Rider mode
        if: matrix.mode == 'Rider'
        run: echo '#define __rider__' >> include/common/mode.h

      - name: Enables custom mode
        run: echo '#define ${{ matrix.mode2 }}' >> include/common/mode.h

      - name: Compiles EA (MQL4)
        uses: fx31337/mql-compile-action@master
        with:
          include: src
          path: src/EA31337.mq4
          verbose: true

      - name: Compiles EA (MQL5)
        uses: fx31337/mql-compile-action@master
        with:
          include: src
          path: src/EA31337.mq5
          verbose: true

      - name: Moves file (MQL4)
        run: mv -v *.ex4 "EA31337-${{ matrix.mode }}-${{ github.sha }}.ex4"
      - name: Moves file (MQL5)
        run: mv -v *.ex5 "EA31337-${{ matrix.mode }}-${{ github.sha }}.ex5"

      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: EA31337-${{ matrix.mode }}
          path: '**/EA*.ex?'

  Backtest-Lite:
    defaults:
      run:
        shell: bash
    needs: Compile-EA
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        exclude:
          - deposit: 1k
            mode: Lite
            spread: 10
            year: 2021
        mode: [Lite]
        year: [2021]
        deposit: [1k, 10k, 100k]
        spread: [1, 10]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: EA31337-${{ matrix.mode }}
      - name: Removes old results
        # yamllint disable-line rule:line-length
        run: rm -fr "docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}/_results"/*
      # yamllint disable-line rule:line-length
      - run: docker-compose run ${{ matrix.mode }}_${{ matrix.year }}_${{ matrix.deposit }}_s${{ matrix.spread }}
        # yamllint disable-line rule:line-length
        working-directory: docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}
      - name: Uploads results
        uses: actions/upload-artifact@v3
        with:
          name: Results-${{ matrix.mode }}-${{ matrix.year }}
          # yamllint disable-line rule:line-length
          path: docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}/_results
      - name: Re-uploads results on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Results-${{ matrix.mode }}-${{ matrix.year }}
          # yamllint disable-line rule:line-length
          path: docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}/_results

  Backtest-Advanced:
    defaults:
      run:
        shell: bash
    needs: Compile-EA
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        exclude:
          - deposit: 1k
            mode: Advanced
            spread: 10
            year: 2021
        mode: [Advanced]
        year: [2021]
        deposit: [1k, 10k, 100k]
        spread: [1, 10]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: EA31337-${{ matrix.mode }}
      - name: Removes old results
        # yamllint disable-line rule:line-length
        run: rm -fr "docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}/_results"/*
      # yamllint disable-line rule:line-length
      - run: docker-compose run ${{ matrix.mode }}_${{ matrix.year }}_${{ matrix.deposit }}_s${{ matrix.spread }}
        # yamllint disable-line rule:line-length
        working-directory: docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}
      - name: Uploads results
        uses: actions/upload-artifact@v3
        with:
          name: Results-${{ matrix.mode }}-${{ matrix.year }}
          # yamllint disable-line rule:line-length
          path: docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}/_results
      - name: Re-uploads results on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Results-${{ matrix.mode }}-${{ matrix.year }}
          # yamllint disable-line rule:line-length
          path: docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}/_results

  Backtest-Rider:
    defaults:
      run:
        shell: bash
    needs: Compile-EA
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        exclude:
          - deposit: 1k
            mode: Rider
            spread: 10
            year: 2021
        mode: [Rider]
        year: [2021]
        deposit: [1k, 10k, 100k]
        spread: [1, 10]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: EA31337-${{ matrix.mode }}
      - name: Removes old results
        # yamllint disable-line rule:line-length
        run: rm -fr "docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}/_results"/*
      # yamllint disable-line rule:line-length
      - run: docker-compose run ${{ matrix.mode }}_${{ matrix.year }}_${{ matrix.deposit }}_s${{ matrix.spread }}
        # yamllint disable-line rule:line-length
        working-directory: docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}
      - name: Uploads results
        uses: actions/upload-artifact@v3
        with:
          name: Results-${{ matrix.mode }}-${{ matrix.year }}
          # yamllint disable-line rule:line-length
          path: docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}/_results
      - name: Re-uploads results on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Results-${{ matrix.mode }}-${{ matrix.year }}
          # yamllint disable-line rule:line-length
          path: docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}/_results


  Publish-Results:
    defaults:
      run:
        shell: bash
        working-directory: docker/backtest
    if: >
      github.repository == 'EA31337/EA31337'
      && github.event_name == 'pull_request'
      && ${{ always() }}
    needs: [Backtest-Lite, Backtest-Advanced, Backtest-Rider]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode:
          - Lite
          - Advanced
          - Rider
        year:
          - 2021
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
          ref: ${{ github.ref }}
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
          ref: refs/heads/${{ github.head_ref }}
      - uses: actions/download-artifact@v3
        with:
          name: Results-${{ matrix.mode }}-${{ matrix.year }}
          # yamllint disable-line rule:line-length
          path: docker/backtest/${{ matrix.mode }}/all-yearly/${{ matrix.year }}/_results
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email $git_email
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin "${{ github.ref }}" --autostash --rebase -Xours
          git commit -a \
          -m "${{ matrix.mode }}: Backtest Results for ${{ matrix.year }}"
        env:
          git_email: "${{ github.actor }}@users.noreply.github.com"
      - name: Push changes (not PR)
        if: github.event_name != 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes (PR)
        if: github.event_name == 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          branch: refs/heads/${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Re-pull on failure
        if: ${{ failure() }}
        run: git pull origin ${{ github.ref }} --autostash --rebase -X ours
