---
name: Compile

on:
  pull_request:
    paths:
      - '**/*.mq?'
      - '.github/workflows/compile.yml'
      - '.github/workflows/scripts/compile.ps1'
      - 'src/include/**'
  push:
    branches:
      - 'master'
      - 'ci'
      - '*dev*'
    paths:
      - '**/*.mq?'
      - '.github/workflows/compile.yml'
      - '.github/workflows/scripts/compile.ps1'
      - 'src/include/**'

jobs:
  Compile:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Compile
        run: .\.github\workflows\scripts\compile.ps1
        shell: powershell
