---
name: Compile

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  Compile:

    runs-on: windows-latest

    strategy:
      matrix:
        mode:
          - Lite
          - Advanced
          - Rider
        mode2:
          - __input__
          - __resource__

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Enables CLI mode
        run: echo '#define __cli__' > src/include/common/mode.h

      - name: Enables Advanced mode
        if: matrix.mode == 'Advanced'
        run: echo '#define __advanced__' >> src/include/common/mode.h

      - name: Enables Rider mode
        if: matrix.mode == 'Rider'
        run: echo '#define __rider__' >> src/include/common/mode.h

      - name: Enables custom mode
        run: echo '#define ${{ matrix.mode2 }}' >> src/include/common/mode.h

      - name: Compiles EA (MQL4)
        uses: fx31337/mql-compile-action@master
        with:
          include: src
          path: src\EA31337.mq4
          verbose: true

      - name: Compiles EA (MQL5)
        uses: fx31337/mql-compile-action@master
        with:
          include: src
          path: src\EA31337.mq5
          verbose: true

      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EA31337-${{ matrix.mode }}
          path: 'src/*.ex?'
