---
name: Test

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '**.h'
      - '**.mq?'
      - .github/workflows/test.yml
      - src/*.mq?
      - src/*.mq[45h]
      - src/include/**
  push:
    paths:
      - '**.h'
      - '**.mq?'
      - .github/workflows/test.yml
      - src/*.mq?
      - src/*.mq[45h]
      - src/include/**

jobs:
  Compile:

    runs-on: windows-latest

    strategy:
      matrix:
        mode:
          - Lite
          - Advanced
          - Rider

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Enables Advanced mode
        if: matrix.mode == 'Advanced'
        run: echo '#define __advanced__' > src/include/common/mode.h

      - name: Enables Rider mode
        if: matrix.mode == 'Rider'
        run: echo '#define __rider__' > src/include/common/mode.h

      - name: Compiles EA (MQL4)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337.mq4
          verbose: true

      - name: Compiles EA (MQL5)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337.mq5
          verbose: true

      - name: Moves file (MQL4)
        run: mv -v src\*.ex4 "EA31337-${{ matrix.mode }}-${{ github.sha }}.ex4"

      - name: Moves file (MQL5)
        run: mv -v src\*.ex5 "EA31337-${{ matrix.mode }}-${{ github.sha }}.ex5"

      - name: Prints compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
        shell: powershell

      - name: Uploads artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.mode }}
          path: '*.ex?'

  Test:

    defaults:
      run:
        shell: bash

    needs: Compile
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mode:
          - Lite
          - Advanced
          - Rider
        month: [1, 2]
        year: [2019]

    steps:

      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.mode }}

      - name: Test ${{ matrix.year }}.${{ matrix.month }}
        uses: fx31337/mql-tester-action@master
        with:
          BtDeposit: 10000
          BtDigits: 5
          BtMonths: ${{ matrix.month }}
          BtYears: ${{ matrix.year }}
          RunOnWarning: 'show_logs && parse_results $@'
          TestExpert: EA31337-${{ matrix.mode }}

  Release:

    defaults:
      run:
        shell: bash

    if: github.event_name == 'push'

    needs: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mode:
          - Lite
          - Advanced
          - Rider
      max-parallel: 1

    steps:

      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: myref

      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.mode }}

      - name: Adjust EA filenames for release
        run: >
          mv -v
          EA31337-${{ matrix.mode }}-${{ github.sha }}.ex4
          EA31337-${{ matrix.mode }}-${GITHUB_REF#refs/heads/}.ex4 &&
          mv -v
          EA31337-${{ matrix.mode }}-${{ github.sha }}.ex5
          EA31337-${{ matrix.mode }}-${GITHUB_REF#refs/heads/}.ex5

      - name: Create version file
        run: echo ${{ github.sha }} > version.txt
        shell: bash

      - name: Create Development Release
        uses: softprops/action-gh-release@v1
        if: >
          startsWith(github.ref, 'refs/heads/v') &&
          endsWith(github.ref, '-dev')
        with:
          files: |
            EA31337-${{ matrix.mode }}-${{ steps.myref.outputs.branch }}.ex?
            *.txt
          name: Development Release (${{ steps.myref.outputs.branch }})
          prerelease: true
          tag_name: ${{ steps.myref.outputs.branch }}-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag Release
        uses: softprops/action-gh-release@v1
        if: contains( github.ref, 'refs/tags/v' )
        with:
          files: |
            EA31337-${{ matrix.mode }}-${{ steps.myref.outputs.branch }}.ex?
          name: EA31337 ${{ steps.myref.outputs.branch }}
          prerelease: true
          tag_name: ${{ steps.myref.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
