---
name: Test Docker

on:
  pull_request:
    paths:
      - '**/*.h'
      - '**/*.mq?'
      - '.github/workflows/test-docker.yml'
  push:
    paths:
      - '**/*.h'
      - '**/*.mq?'
      - '.github/workflows/test-docker.yml'

jobs:
  Lite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build image for 2018
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: docker-compose build
        working-directory: docker/tests/lite
      - name: Run test for 2018.01
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          RUN_ON_WARNING: 'show_logs && parse_results $@ && exit 0'
        run: docker-compose run -e RUN_ON_WARNING lite_test_2018_01
        working-directory: docker/tests/lite
      - name: Run test for 2018.02
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          RUN_ON_WARNING: 'show_logs && parse_results $@ && exit 0'
        run: docker-compose run -e RUN_ON_WARNING lite_test_2018_02
        working-directory: docker/tests/lite
