---
name: Tests

on:
  pull_request:
    paths-ignore:
      - '*.json'
      - '*.md'
      - '*.txt'
      - '.git*'
      - '.yamllint'
      - 'LICENSE'
  push:
    branches:
      - 'master'
      - 'ci'
      - '*dev*'
    paths-ignore:
      - '*.md'

jobs:
  Lite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Test 2018.01
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 1
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && git diff && exit 0'
          RunOnSuccess: 'git diff'
      - name: Test 2018.02
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 2
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && git diff && exit 0'
          RunOnSuccess: 'git diff'
  Advanced:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Sets mode
        run: "make set-advanced"
      - name: Test 2018.01
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 1
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && git diff && exit 0'
          RunOnSuccess: 'git diff'
      - name: Test 2018.02
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 2
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && git diff && exit 0'
          RunOnSuccess: 'git diff'
  Rider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Sets mode
        run: "make set-rider"
      - name: Test 2018.01
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 1
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && git diff && exit 0'
          RunOnSuccess: 'git diff'
      - name: Test 2018.02
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 2
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && git diff && exit 0'
          RunOnSuccess: 'git diff'
