---
name: Test

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '**.h'
      - '**.mq?'
      - .github/workflows/test.yml
      - src/*.mq?
      - src/*.mq[45h]
      - src/include/**
  push:
    paths:
      - '**.h'
      - '**.mq?'
      - .github/workflows/test.yml
      - src/*.mq?
      - src/*.mq[45h]
      - src/include/**

jobs:

  Compile-IndicatorsOther:
    defaults:
      run:
        shell: powershell
        working-directory: src/indicators-other
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/checkout@v2
        with:
          path: Include/EA31337-classes
          ref: v2.010
          repository: EA31337/EA31337-classes
      - name: Compile (build 2361)
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 5.0.0.2361
          path: src/indicators-other/**/*.mq?
          verbose: true
      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
      - run: Get-Location
      - name: Upload indicator artifacts
        uses: actions/upload-artifact@v2
        with:
          name: indicators-other
          path: '**/*.ex?'

  Compile-EA:

    defaults:
      run:
        shell: powershell
        working-directory: src
    needs: [Compile-IndicatorsOther]
    runs-on: windows-latest

    strategy:
      matrix:
        mode:
          - Lite
          - Advanced
          - Rider
        mode2:
          - __resource__

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: actions/download-artifact@v2
        with:
          name: indicators-other
          path: .

      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'

      - run: Get-Location

      # @fixme: https://github.com/actions/upload-artifact/issues/87
      - name: Link indicators
        run: New-Item -ItemType SymbolicLink -Path "../indicators-other" -Target "indicators-other"

      - name: Enables CLI mode
        run: echo '#define __cli__' > include/common/mode.h

      - name: Enables Advanced mode
        if: matrix.mode == 'Advanced'
        run: echo '#define __advanced__' >> include/common/mode.h

      - name: Enables Rider mode
        if: matrix.mode == 'Rider'
        run: echo '#define __rider__' >> include/common/mode.h

      - name: Enables custom mode
        run: echo '#define ${{ matrix.mode2 }}' >> include/common/mode.h

      - name: Compiles EA (MQL4)
        uses: fx31337/mql-compile-action@master
        with:
          include: src
          path: src/EA31337.mq4
          verbose: true

      - name: Compiles EA (MQL5)
        uses: fx31337/mql-compile-action@master
        with:
          include: src
          path: src/EA31337.mq5
          verbose: true

      - name: Moves file (MQL4)
        run: mv -v *.ex4 "EA31337-${{ matrix.mode }}-${{ github.sha }}.ex4"
      - name: Moves file (MQL5)
        run: mv -v *.ex5 "EA31337-${{ matrix.mode }}-${{ github.sha }}.ex5"

      - name: List compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: EA31337-${{ matrix.mode }}
          path: '**/EA*.ex?'

  Test:

    defaults:
      run:
        shell: bash

    needs: Compile-EA
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        mode:
          - Lite
          - Advanced
          - Rider
        month: [1, 2]
        year: [2020]

    steps:

      - uses: actions/download-artifact@v2
        with:
          name: EA31337-${{ matrix.mode }}

      - name: Test ${{ matrix.year }}.${{ matrix.month }}
        uses: fx31337/mql-tester-action@master
        with:
          BtDeposit: 10000
          BtDigits: 5
          BtMonths: ${{ matrix.month }}
          BtYears: ${{ matrix.year }}
          TestExpert: EA31337-${{ matrix.mode }}
          TestPeriod: M15
