---
name: Tests

on:
  - pull_request
  - push

jobs:
  Lite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Monthly Tests (Lite)
      working-directory: docker/tests/lite
      run: docker-compose up
      env:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1
