---
name: Test

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '**.h'
      - '**.mq?'
      - .github/workflows/test.yml
      - src/*.mq?
      - src/*.mq[45h]
      - src/include/**
  push:
    paths:
      - '**.h'
      - '**.mq?'
      - .github/workflows/test.yml
      - src/*.mq?
      - src/*.mq[45h]
      - src/include/**

jobs:
  Compile:

    runs-on: windows-latest

    strategy:
      matrix:
        mode:
          - Lite
          - Advanced
          - Rider

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Enables CLI mode
        run: echo '#define __cli__' > src/include/common/mode.h

      - name: Enables release mode
        run: echo '#define __release__' >> src/include/common/mode.h

      - name: Enables Advanced mode
        if: matrix.mode == 'Advanced'
        run: echo '#define __advanced__' >> src/include/common/mode.h

      - name: Enables Rider mode
        if: matrix.mode == 'Rider'
        run: echo '#define __rider__' >> src/include/common/mode.h

      - name: Compiles EA (MQL4)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337.mq4
          verbose: true

      - name: Compiles EA (MQL5)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337.mq5
          verbose: true

      - name: Moves file (MQL4)
        run: mv -v src\*.ex4 "EA31337-${{ matrix.mode }}-${{ github.sha }}.ex4"

      - name: Moves file (MQL5)
        run: mv -v src\*.ex5 "EA31337-${{ matrix.mode }}-${{ github.sha }}.ex5"

      - name: Prints compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
        shell: powershell

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.mode }}
          path: '*.ex?'

  Test:

    defaults:
      run:
        shell: bash

    needs: Compile
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mode:
          - Lite
          - Advanced
          - Rider
        month: [1, 2]
        year: [2020]

    steps:

      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.mode }}

      - name: Test ${{ matrix.year }}.${{ matrix.month }}
        uses: fx31337/mql-tester-action@master
        with:
          BtDeposit: 10000
          BtDigits: 5
          BtMonths: ${{ matrix.month }}
          BtYears: ${{ matrix.year }}
          RunOnError: 'show_logs && parse_results $@; exit 0'
          TestExpert: EA31337-${{ matrix.mode }}
          TestPeriod: M1
