---
name: Test

on:
  pull_request:
    paths:
      - '**/*.h'
      - '**/*.mq?'
      - '.github/workflows/test.yml'
      - 'src/include/**'
  push:
    paths:
      - '**/*.h'
      - '**/*.mq?'
      - '.github/workflows/test.yml'
      - 'src/include/**'
  release:
    types:
      - prereleased
      - published
      - unpublished

jobs:
  Compile-Lite:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Enables Lite mode
        run: echo '#define __release__' > src/include/EA31337/ea-mode.mqh
      - name: Compiles EA (MQL4)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337.mq4
          verbose: true
      - name: Compiles EA (MQL5)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337.mq5
          verbose: true
      - name: Moves file (MQL4)
        run: mv -v src\*.ex4 "EA31337-Lite-${{ github.sha }}.ex4"
      - name: Moves file (MQL5)
        run: mv -v src\*.ex5 "EA31337-Lite-${{ github.sha }}.ex5"
      - name: Prints compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
        shell: powershell
      - name: Uploads artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ea-lite
          path: '*.ex?'
  Compile-Advanced:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Enables Advanced mode
        run: echo '#define __advanced__' > src/include/EA31337/ea-mode.mqh
      - name: Compiles EA (MQL4)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337.mq4
          verbose: true
      - name: Compiles EA (MQL5)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337.mq5
          verbose: true
      - name: Moves file (MQL4)
        run: mv -v src\*.ex4 "EA31337-Advanced-${{ github.sha }}.ex4"
      - name: Moves file (MQL5)
        run: mv -v src\*.ex5 "EA31337-Advanced-${{ github.sha }}.ex5"
      - name: Prints compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
        shell: powershell
      - name: Uploads artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ea-advanced
          path: '*.ex?'
  Compile-Rider:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Enables Rider mode
        run: echo '#define __rider__' > src/include/EA31337/ea-mode.mqh
      - name: Compiles EA (MQL4)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337.mq4
          verbose: true
      - name: Compiles EA (MQL5)
        uses: fx31337/mql-compile-action@master
        with:
          path: src\EA31337.mq5
          verbose: true
      - name: Moves file (MQL4)
        run: mv -v src\*.ex4 "EA31337-Rider-${{ github.sha }}.ex4"
      - name: Moves file (MQL5)
        run: mv -v src\*.ex5 "EA31337-Rider-${{ github.sha }}.ex5"
      - name: Prints compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
        shell: powershell
      - name: Uploads artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ea-rider
          path: '*.ex?'
  Test-Lite:
    needs: Compile-Lite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ea-lite
      - name: Test 2018.01
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 1
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
      - name: Test 2018.02
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 2
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
      - name: Test 2019.01
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 1
          BtYears: 2019
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
        if: false
      - name: Test 2019.02
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 2
          BtYears: 2019
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
        if: false
  Test-Advanced:
    needs: Compile-Advanced
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ea-advanced
      - name: Test 2018.01
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 1
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
      - name: Test 2018.02
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 2
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
      - name: Test 2019.01
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 1
          BtYears: 2019
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
        if: false
      - name: Test 2019.02
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 2
          BtYears: 2019
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
        if: false
  Test-Rider:
    needs: Compile-Rider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ea-rider
      - name: Test 2018.01
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 1
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
      - name: Test 2018.02
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 2
          BtYears: 2018
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
      - name: Test 2019.01
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 1
          BtYears: 2019
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
        if: false
      - name: Test 2019.02
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          BtMonths: 2
          BtYears: 2019
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
        if: false
  Create-Release:
    needs: [Compile-Lite, Compile-Advanced, Compile-Rider]
    runs-on: ubuntu-latest
    steps:
      - name: Prints github.ref
        run: echo ${{ github.ref }}
      - name: Create Development Release
        id: release_dev
        if: endsWith( github.ref, '-dev' )
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Development Release ${{ github.ref }}
          body: |
            This is the latest development version for testing purposes (not suitable for trading).
            Please use the stable release instead.
          draft: true
          prerelease: true
      - name: Create Tagged Release
        id: release_tag
        if: contains( github.ref, 'refs/tags/v' )
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is the latest pre-released version.
            Use it with caution.
          draft: false
          prerelease: true
  Release-Lite:
    needs: Create-Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ea-lite
      - name: Adjust filename
        run: mv -v *.ex4 "EA31337-Lite-${GITHUB_BRANCH##*/}.ex4"
        env:
          GITHUB_BRANCH: ${{ github.ref }}
  Release-Advanced:
    needs: Create-Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ea-advanced
      - name: Adjust filename
        run: mv -v *.ex4 "EA31337-Advanced-${GITHUB_BRANCH##*/}.ex4"
        env:
          GITHUB_BRANCH: ${{ github.ref }}
  Release-Rider:
    needs: Create-Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ea-rider
      - name: Adjust filename
        run: mv -v *.ex4 "EA31337-Rider-${GITHUB_BRANCH##*/}.ex4"
        env:
          GITHUB_BRANCH: ${{ github.ref }}
